apiVersion: v1
kind: Service
metadata:
  name: static-web
  namespace: my-app
spec:
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: 8080      # External port
      targetPort: 80  # Internal container port
  type: LoadBalancer
